# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.srcs/sources_1/bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0.xci
# IP: The module: 'CB4CLED_bd_int_CS_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.gen/sources_1/bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CB4CLED_bd_int_CS_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.gen/sources_1/bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CB4CLED_bd_int_CS_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.gen/sources_1/bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CB4CLED_bd_int_CS_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.srcs/sources_1/bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0.xci
# IP: The module: 'CB4CLED_bd_int_CS_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.gen/sources_1/bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CB4CLED_bd_int_CS_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.gen/sources_1/bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CB4CLED_bd_int_CS_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.gen/sources_1/bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CB4CLED_bd_int_CS_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
