@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Oct 10 09:09:13 +0100 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim RISCV_ALU_TB_behav -key {Behavioral:sim_1:Functional:RISCV_ALU_TB} -tclbatch RISCV_ALU_TB.tcl -view C:/2023/HDLGenTop/myFiles/HDLGen-ChatGPT/User_Projects/RISCV/RISCV_ALU/Verilog/AMDPrj/RISCV_ALU_TB_behav.wcfg -log simulate.log"
call xsim  RISCV_ALU_TB_behav -key {Behavioral:sim_1:Functional:RISCV_ALU_TB} -tclbatch RISCV_ALU_TB.tcl -view C:/2023/HDLGenTop/myFiles/HDLGen-ChatGPT/User_Projects/RISCV/RISCV_ALU/Verilog/AMDPrj/RISCV_ALU_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
