# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/generated/physical_constr.xdc

# Block Designs: bd/CB4CLED_bd/CB4CLED_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd || ORIG_REF_NAME==CB4CLED_bd} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_CB4CLED_0_0/CB4CLED_bd_CB4CLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_CB4CLED_0_0 || ORIG_REF_NAME==CB4CLED_bd_CB4CLED_0_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_processing_system7_0_0/CB4CLED_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_processing_system7_0_0 || ORIG_REF_NAME==CB4CLED_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_clk_0/CB4CLED_bd_clk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_clk_0 || ORIG_REF_NAME==CB4CLED_bd_clk_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_rst_0/CB4CLED_bd_rst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_rst_0 || ORIG_REF_NAME==CB4CLED_bd_rst_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_load_0/CB4CLED_bd_load_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_load_0 || ORIG_REF_NAME==CB4CLED_bd_load_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_loadDat_0/CB4CLED_bd_loadDat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_loadDat_0 || ORIG_REF_NAME==CB4CLED_bd_loadDat_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_ce_0/CB4CLED_bd_ce_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_ce_0 || ORIG_REF_NAME==CB4CLED_bd_ce_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_up_0/CB4CLED_bd_up_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_up_0 || ORIG_REF_NAME==CB4CLED_bd_up_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_count_0/CB4CLED_bd_count_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_count_0 || ORIG_REF_NAME==CB4CLED_bd_count_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_TC_0/CB4CLED_bd_TC_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_TC_0 || ORIG_REF_NAME==CB4CLED_bd_TC_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_ceo_0/CB4CLED_bd_ceo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_ceo_0 || ORIG_REF_NAME==CB4CLED_bd_ceo_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_int_intTC_0/CB4CLED_bd_int_intTC_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_int_intTC_0 || ORIG_REF_NAME==CB4CLED_bd_int_intTC_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_int_CS_0/CB4CLED_bd_int_CS_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_int_CS_0 || ORIG_REF_NAME==CB4CLED_bd_int_CS_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_int_NS_0/CB4CLED_bd_int_NS_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_int_NS_0 || ORIG_REF_NAME==CB4CLED_bd_int_NS_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_xbar_0/CB4CLED_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_xbar_0 || ORIG_REF_NAME==CB4CLED_bd_xbar_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_auto_pc_0/CB4CLED_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_auto_pc_0 || ORIG_REF_NAME==CB4CLED_bd_auto_pc_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_axi_interconnect_0_0/CB4CLED_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_axi_interconnect_0_0 || ORIG_REF_NAME==CB4CLED_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/CB4CLED_bd/ip/CB4CLED_bd_proc_sys_reset_0_0/CB4CLED_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CB4CLED_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==CB4CLED_bd_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/videodemo/Sequential/Sequential/Counters/CB4CLED/Verilog/AMDprj/CB4CLED.gen/sources_1/bd/CB4CLED_bd/CB4CLED_bd_ooc.xdc
