# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/generated/physical_constr.xdc

# Block Designs: bd/RISCV_RB_bd/RISCV_RB_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd || ORIG_REF_NAME==RISCV_RB_bd} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_RISCV_RB_0_0/RISCV_RB_bd_RISCV_RB_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_RISCV_RB_0_0 || ORIG_REF_NAME==RISCV_RB_bd_RISCV_RB_0_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_processing_system7_0_0/RISCV_RB_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_processing_system7_0_0 || ORIG_REF_NAME==RISCV_RB_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_RWr_0/RISCV_RB_bd_RWr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_RWr_0 || ORIG_REF_NAME==RISCV_RB_bd_RWr_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_rd_0 || ORIG_REF_NAME==RISCV_RB_bd_rd_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_rs1_0/RISCV_RB_bd_rs1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_rs1_0 || ORIG_REF_NAME==RISCV_RB_bd_rs1_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_rs2_0/RISCV_RB_bd_rs2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_rs2_0 || ORIG_REF_NAME==RISCV_RB_bd_rs2_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_rs1D_0/RISCV_RB_bd_rs1D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_rs1D_0 || ORIG_REF_NAME==RISCV_RB_bd_rs1D_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_rs2D_0/RISCV_RB_bd_rs2D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_rs2D_0 || ORIG_REF_NAME==RISCV_RB_bd_rs2D_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_WBDat_0/RISCV_RB_bd_WBDat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_WBDat_0 || ORIG_REF_NAME==RISCV_RB_bd_WBDat_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_ce_0/RISCV_RB_bd_ce_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_ce_0 || ORIG_REF_NAME==RISCV_RB_bd_ce_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_clk_0/RISCV_RB_bd_clk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_clk_0 || ORIG_REF_NAME==RISCV_RB_bd_clk_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_rst_0/RISCV_RB_bd_rst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_rst_0 || ORIG_REF_NAME==RISCV_RB_bd_rst_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_xbar_0/RISCV_RB_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_xbar_0 || ORIG_REF_NAME==RISCV_RB_bd_xbar_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_auto_pc_0/RISCV_RB_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_auto_pc_0 || ORIG_REF_NAME==RISCV_RB_bd_auto_pc_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_axi_interconnect_0_0/RISCV_RB_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_axi_interconnect_0_0 || ORIG_REF_NAME==RISCV_RB_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/RISCV_RB_bd/ip/RISCV_RB_bd_proc_sys_reset_0_0/RISCV_RB_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_RB_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==RISCV_RB_bd_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/RISCV_RB_bd/RISCV_RB_bd_ooc.xdc
