// Title Section Start
// Generated by HDLGen, Github https://github.com/HDLGen-ChatGPT/HDLGen-ChatGPT, on 24-September-2024 at 12:57

// Component Name : Mux2_1
// Title          : 2-to-1 Multiplexer

// Author(s)      : Luke Canny
// Organisation   : University of Galway
// Email          : l.canny3@universityofgalway.ie
// Date           : 24/09/2024

// Description
// 2-bit input, 1-bit output multiplexer

// Entity signal dictionary
// dIn0   : datapath 0
// dIn1   : datapath 1
// sel    : selector
// dOut   : datapath out

// Internal signal dictionary
// None

// Title Section End

// Module declaration
module Mux2_1(
		dIn0,
		dIn1,
		sel,
		dOut
	);

	// Port definitions
	input  dIn0;
	input  dIn1;
	input  sel;
	output dOut;

    reg  dOut;

    // Internal signal declarations
    // None

    always @(sel or dIn0 or dIn1)
    begin : asgnOutput_p
    	dOut = dIn0; // Default assignment
    	if (sel == 1'b1) // if sel == 1'b1 then
    		dOut = dIn1; // dOut <= dIn1
    end

endmodule
