# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.srcs/sources_1/bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0.xci
# IP: The module: 'singleShot_bd_rst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.gen/sources_1/bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'singleShot_bd_rst_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.gen/sources_1/bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'singleShot_bd_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.gen/sources_1/bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'singleShot_bd_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.srcs/sources_1/bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0.xci
# IP: The module: 'singleShot_bd_rst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.gen/sources_1/bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'singleShot_bd_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.gen/sources_1/bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'singleShot_bd_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.gen/sources_1/bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'singleShot_bd_rst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
