# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/videodemo/HDLGen-ChatGPT/User_Projects/RISCV_RB/RISCV_RB/VHDL/AMDprj/RISCV_RB.srcs/sources_1/bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0.xci
# IP: The module: 'RISCV_RB_bd_rd_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/RISCV_RB/RISCV_RB/VHDL/AMDprj/RISCV_RB.srcs/sources_1/bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_RB_bd_rd_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/RISCV_RB/RISCV_RB/VHDL/AMDprj/RISCV_RB.srcs/sources_1/bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_RB_bd_rd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/RISCV_RB/RISCV_RB/VHDL/AMDprj/RISCV_RB.srcs/sources_1/bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_RB_bd_rd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/videodemo/HDLGen-ChatGPT/User_Projects/RISCV_RB/RISCV_RB/VHDL/AMDprj/RISCV_RB.srcs/sources_1/bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0.xci
# IP: The module: 'RISCV_RB_bd_rd_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/RISCV_RB/RISCV_RB/VHDL/AMDprj/RISCV_RB.srcs/sources_1/bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_RB_bd_rd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/RISCV_RB/RISCV_RB/VHDL/AMDprj/RISCV_RB.srcs/sources_1/bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_RB_bd_rd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/RISCV_RB/RISCV_RB/VHDL/AMDprj/RISCV_RB.srcs/sources_1/bd/RISCV_RB_bd/ip/RISCV_RB_bd_rd_0/RISCV_RB_bd_rd_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_RB_bd_rd_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
