# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/generated/physical_constr.xdc

# Block Designs: bd/singleShot_bd/singleShot_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd || ORIG_REF_NAME==singleShot_bd} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_singleShot_0_0_1/singleShot_bd_singleShot_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_singleShot_0_0 || ORIG_REF_NAME==singleShot_bd_singleShot_0_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_processing_system7_0_0_1/singleShot_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_processing_system7_0_0 || ORIG_REF_NAME==singleShot_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_sw_0_1/singleShot_bd_sw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_sw_0 || ORIG_REF_NAME==singleShot_bd_sw_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_aShot_0_1/singleShot_bd_aShot_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_aShot_0 || ORIG_REF_NAME==singleShot_bd_aShot_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_clk_0_1/singleShot_bd_clk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_clk_0 || ORIG_REF_NAME==singleShot_bd_clk_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_rst_0_1/singleShot_bd_rst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_rst_0 || ORIG_REF_NAME==singleShot_bd_rst_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_xbar_0_1/singleShot_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_xbar_0 || ORIG_REF_NAME==singleShot_bd_xbar_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_auto_pc_0_1/singleShot_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_auto_pc_0 || ORIG_REF_NAME==singleShot_bd_auto_pc_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_axi_interconnect_0_0_1/singleShot_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_axi_interconnect_0_0 || ORIG_REF_NAME==singleShot_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/singleShot_bd/ip/singleShot_bd_proc_sys_reset_0_0_1/singleShot_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singleShot_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==singleShot_bd_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/videodemo/FiniteStateMachines_FSMs/singleShot/VHDL/AMDprj/singleShot.gen/sources_1/bd/singleShot_bd/singleShot_bd_ooc.xdc
