# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/generated/physical_constr.xdc

# Block Designs: bd/Mux2_1_bd/Mux2_1_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd || ORIG_REF_NAME==Mux2_1_bd} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_Mux2_1_0_0_2/Mux2_1_bd_Mux2_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_Mux2_1_0_0 || ORIG_REF_NAME==Mux2_1_bd_Mux2_1_0_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_processing_system7_0_0_2/Mux2_1_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_processing_system7_0_0 || ORIG_REF_NAME==Mux2_1_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_dIn0_0_2/Mux2_1_bd_dIn0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_dIn0_0 || ORIG_REF_NAME==Mux2_1_bd_dIn0_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_dIn1_0_2/Mux2_1_bd_dIn1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_dIn1_0 || ORIG_REF_NAME==Mux2_1_bd_dIn1_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_sel_0_2/Mux2_1_bd_sel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_sel_0 || ORIG_REF_NAME==Mux2_1_bd_sel_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_dOut_0_2/Mux2_1_bd_dOut_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_dOut_0 || ORIG_REF_NAME==Mux2_1_bd_dOut_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_xbar_0_2/Mux2_1_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_xbar_0 || ORIG_REF_NAME==Mux2_1_bd_xbar_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_auto_pc_0_2/Mux2_1_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_auto_pc_0 || ORIG_REF_NAME==Mux2_1_bd_auto_pc_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_axi_interconnect_0_0_2/Mux2_1_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_axi_interconnect_0_0 || ORIG_REF_NAME==Mux2_1_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Mux2_1_bd/ip/Mux2_1_bd_proc_sys_reset_0_0_2/Mux2_1_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Mux2_1_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==Mux2_1_bd_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/Mux2_1/Verilog/AMDprj/Mux2_1.gen/sources_1/bd/Mux2_1_bd/Mux2_1_bd_ooc.xdc
