# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/generated/physical_constr.xdc

# Block Designs: bd/RISCV_ALU_bd/RISCV_ALU_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd || ORIG_REF_NAME==RISCV_ALU_bd} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_RISCV_ALU_0_0_2/RISCV_ALU_bd_RISCV_ALU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_RISCV_ALU_0_0 || ORIG_REF_NAME==RISCV_ALU_bd_RISCV_ALU_0_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_processing_system7_0_0_2/RISCV_ALU_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_processing_system7_0_0 || ORIG_REF_NAME==RISCV_ALU_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_selALUOp_0_2/RISCV_ALU_bd_selALUOp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_selALUOp_0 || ORIG_REF_NAME==RISCV_ALU_bd_selALUOp_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_A_0_2/RISCV_ALU_bd_A_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_A_0 || ORIG_REF_NAME==RISCV_ALU_bd_A_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_B_0_2/RISCV_ALU_bd_B_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_B_0 || ORIG_REF_NAME==RISCV_ALU_bd_B_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_ALUOut_0_2/RISCV_ALU_bd_ALUOut_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_ALUOut_0 || ORIG_REF_NAME==RISCV_ALU_bd_ALUOut_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_branch_0_2/RISCV_ALU_bd_branch_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_branch_0 || ORIG_REF_NAME==RISCV_ALU_bd_branch_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_xbar_0_2/RISCV_ALU_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_xbar_0 || ORIG_REF_NAME==RISCV_ALU_bd_xbar_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_auto_pc_0_2/RISCV_ALU_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_auto_pc_0 || ORIG_REF_NAME==RISCV_ALU_bd_auto_pc_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_axi_interconnect_0_0_2/RISCV_ALU_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_axi_interconnect_0_0 || ORIG_REF_NAME==RISCV_ALU_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/RISCV_ALU_bd/ip/RISCV_ALU_bd_proc_sys_reset_0_0_2/RISCV_ALU_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISCV_ALU_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==RISCV_ALU_bd_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/demo/RISCV/RISCV_ALU/VHDL/AMDprj/RISCV_ALU.gen/sources_1/bd/RISCV_ALU_bd/RISCV_ALU_bd_ooc.xdc
