-- Title Section Start
-- Generated by HDLGen, Github https://github.com/HDLGen-ChatGPT/HDLGen-ChatGPT, on 24-September-2024 at 12:42

-- Component Name : Mux2_1
-- Title          : 2-to-1 Multiplexer

-- Author(s)      : Luke Canny
-- Organisation   : University of Galway
-- Email          : l.canny3@universityofgalway.ie
-- Date           : 24/09/2024

-- Description
-- 2-bit input multiplexer with 1-bit output based on select signal

-- entity signal dictionary
-- dIn0    datapath 0
-- dIn1    datapath 1
-- sel     selector
-- dOut    datapath out

-- internal signal dictionary
-- None

-- Title Section End
-- library declarations
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.MainPackage.all;

-- entity declaration
entity Mux2_1 is 
Port(
    dIn0 : in std_logic;
    dIn1 : in std_logic;
    sel  : in std_logic;
    dOut : out std_logic
);
end entity Mux2_1;

architecture Combinational of Mux2_1 is
-- Internal signal declarations
-- None

begin

asgnOutput_p: process(sel)
begin
    dOut <= dIn0; -- Default assignment

    if sel = '1' then
        dOut <= dIn1;
    end if;
end process;

end Combinational;
