# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/videodemo/HDLGen-ChatGPT/User_Projects/Mux2_1/Verilog/AMDprj/Mux2_1.srcs/sources_1/bd/Mux2_1_bd/ip/Mux2_1_bd_processing_system7_0_0_2/Mux2_1_bd_processing_system7_0_0.xci
# IP: The module: 'Mux2_1_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/Mux2_1/Verilog/AMDprj/Mux2_1.gen/sources_1/bd/Mux2_1_bd/ip/Mux2_1_bd_processing_system7_0_0_2/Mux2_1_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mux2_1_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/videodemo/HDLGen-ChatGPT/User_Projects/Mux2_1/Verilog/AMDprj/Mux2_1.srcs/sources_1/bd/Mux2_1_bd/ip/Mux2_1_bd_processing_system7_0_0_2/Mux2_1_bd_processing_system7_0_0.xci
# IP: The module: 'Mux2_1_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/videodemo/HDLGen-ChatGPT/User_Projects/Mux2_1/Verilog/AMDprj/Mux2_1.gen/sources_1/bd/Mux2_1_bd/ip/Mux2_1_bd_processing_system7_0_0_2/Mux2_1_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mux2_1_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
